name: flutter_auth_session_example
description: Demo for flutter_auth_session_kit.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_auth_session_kit:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
